set_property SRC_FILE_INFO {cfile:C:/Users/inias/Desktop/ap/j1s2/FPGA/VHDL/labo5/D_FF/D_FF.srcs/constrs_1/imports/FPGA/Basys3_Master.xdc rfile:../../../D_FF.srcs/constrs_1/imports/FPGA/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {D}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {clr}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {q}]
